DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(250) NOT NULL,
	ADDRESS VARCHAR(250) NOT NULL,
	STATE VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	ZIP VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);
	